wandb_version: 1

model:
  desc: null
  value: c2fpl
dataset:
  desc: null
  value: ucf
seed:
  desc: null
  value: 42
join_ratio:
  desc: null
  value: 0.1
global_epoch:
  desc: null
  value: 25
local_epoch:
  desc: null
  value: 5
finetune_epoch:
  desc: null
  value: 0
test_gap:
  desc: null
  value: 100
eval_test:
  desc: null
  value: 1
eval_train:
  desc: null
  value: 0
local_lr:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.0
weight_decay:
  desc: null
  value: 0.0
verbose_gap:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 128
visible:
  desc: null
  value: 0
global_testset:
  desc: null
  value: 1
straggler_ratio:
  desc: null
  value: 0
straggler_min_local_epoch:
  desc: null
  value: 1
external_model_params_file:
  desc: null
  value: ''
use_cuda:
  desc: null
  value: 1
save_log:
  desc: null
  value: 1
save_model:
  desc: null
  value: 0
save_fig:
  desc: null
  value: 0
save_metrics:
  desc: null
  value: 0
partition:
  desc: null
  value: partition_25.pkl
dataset_args:
  desc: null
  value:
    dataset: ucf
    client_num: 25
    fraction: 0.5
    seed: 42
    split: sample
    alpha: 0.1
    least_samples: 40
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695554236.212441
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
